[package]
name = "kvm_debugger"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
libc = "0.2"
errno = "0.2"
memoffset = "0.9.1"
crossterm = "0.28.1"
kvm-ioctls = "0.17.0"
kvm-bindings = "0.9.0"
pretty_env_logger = "0.5.0"
clap = { version = "4.0", features = ["derive"] }